### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by alinasoy** [TusharVashishth/Threads_clone#1]
When I'm moving page.tsx into (front) root it shows nothing why

**Comment by pr0x1es** [comment]
Your layout.tsx may be incorrect (which was my fix) here is the source code for it that works for me:

``html import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Threads App",
  description: "The Threads app to share your thoughts and much more.",
};

export default function FrontLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        {children}
  );
}
``html
